### ISSUE TITLE
examples and Binder demo ?

### ISSUE THREAD

**Issue by cranmer** [diana-hep/histbook#1]
Thoughts on an examples/ directory with notebooks and the needed hooks for binder?

Example repo:
 https://github.com/jupyterlab/jupyterlab

**Comment by lukasheinrich** [comment]
this is adressed in #3

**Comment by jpivarski** [comment]
[Done](https://mybinder.org/v2/gh/diana-hep/histbook/master?filepath=binder%2Ftutorial.ipynb). Thanks, Lukas!
