### ISSUE TITLE
[feature request]: 2D plots

### ISSUE THREAD

**Issue by kreczko** [diana-hep/histbook#15]
Following up on the comment made on https://stackoverflow.com/questions/50820894/filling-numpy-arrays-slower-than-for-loop-h-fill-vs-h-fill-numpy:
It would be good to replicate 2D plots that are common in HEP like the on http://histogrammar.org/docs/tutorials/python-matplotlib/
![image](https://user-images.githubusercontent.com/1213276/41339509-e5711576-6eec-11e8-997f-ec82694cdde2.png)

Vega-lite has a scatter plot as well as a heatmap (and table binned heatmap):
 - https://vega.github.io/vega-lite/examples/point_2d.html
 - https://vega.github.io/vega-lite/examples/rect_heatmap.html
 - https://vega.github.io/vega-lite/examples/rect_binned_heatmap.html
The latter is probably closest to what we need.

**Comment by jpivarski** [comment]
It's in the [enhancements branch](https://github.com/diana-hep/histbook/tree/enhancements). Try it out and let me know if it's missing anything.

I haven't done the 2D export to ROOT yet, though.

**Comment by jpivarski** [comment]
Oh, the new method is `Hist.heatmap()` or `Hist.heatmap("x", "y")`. The documentation won't propagate through to readthedocs until I merge enhancements to master.
