### ISSUE TITLE
Sensible plotting defaults for trivial cases

### ISSUE THREAD

**Issue by imandr** [diana-hep/histbook#36]
If I have a Hist with only one axis and I want to plot it, it would be convenient for me not to have to re-specify the axis expression. For example,

```
histogram = Hist(bin("x", 10, -5, 5))     # simple one-axis histogram
histogram.fill(...)
histogram.step().to(canvas)      # default: step("x")
```

Sensible defaults exist in more complicated cases:
```
histogram = Hist(bin("x", 10, -5, 5), bin("y", 10, 0, 1))     # simple one-axis histogram
histogram.fill(...)
histogram.heatmap().to(canvas)      # default: heatmap("x", "y")
```

**Comment by jpivarski** [comment]
Try both of these. I'm pretty sure that's how it works. Reopen this if I'm wrong.

**Comment by jpivarski** [comment]
It's what [the documentation says](http://histbook.readthedocs.io/en/latest/plotting.html).

**Comment by imandr** [comment]
Yes, seems to work. You are right. Thanks !
